### ISSUE TITLE
0xjoseph - Add Liquidity to Curve ETH pools will not work

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-07-blueberry-judging#42]
0xjoseph

high

# Add Liquidity to Curve ETH pools will not work
## Summary
The Curve & Convex spell uses the Curve `add_liquidity` function to provide liquidity to curve pools.

This will only work for non-ETH related Curve pools as ETH curve pools will require you to use the native version of ETH.

## Vulnerability Detail
The Curve `add_liquidity` function was written in a way which assumes that all Curve pools with the same number of tokens uses the same interface for providing liquidity, this is not the case.

Here is how they differ:
1. All ETH related pools are payable functions, which **expects** a msg.value when calling the `add_liquidity` function.

Currently, the Curve & Convex Spell contract can only support non-ETH related pools with an interface like so:
`function add_liquidity(uint256[2] calldata, uint256) external;`
`function add_liquidity(uint256[3] calldata, uint256) external;`
 
 But Curve ETH pools uses payable functions where the `msg.value` is **mandatory** like so:
`function add_liquidity(uint256[3] calldata, uint256) external payable;`

![image](https://github.com/sherlock-audit/2023-07-blueberry-JosephSaw/assets/28586597/385dd122-e476-4cdb-8d64-d564e9a7d997)

Code snippet of the `add_liquidity` function inside the frxEth curve pool: https://etherscan.io/address/0xa1f8a6807c402e4a15ef4eba36528a3fed24e577#code
    
## Impact
BlueBerry will not be able to support **any** Curve ETH LSD related tokens, as the `add_liquidity` function signature are incorrect due to the `payable` keyword.

## Code Snippet
- https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/spell/ConvexSpell.sol#L120-L144
- https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/spell/CurveSpell.sol#L107-L140

## Tool used

Manual Review

## Recommendation
There are 2 ways to fix this, the first is easier and more direct, the second method will require a bit of re-structuring to your code.

Do note that this fix applies to **all** ETH related pools such as frxETH/ETH, stETH/ETH, ETH/USDT/BTC, etc

**First Method:**
i. Create a new mapping `isEthPool` (curveLpAddress -> true/false)
ii. Before checking `if (tokens.length == 2)`, you add another check to see if the curve LP is an ETH pool from the mapping above
iii. If it is, you can add liquidity using code like so: `CURVE_ETH_POOL.add_liquidity{value: amount}([amount, 0], 0);`

**Second Method:**
i. You can either create a mapping to save the function interface or pass it in as an argument.
ii. Encode the data dynamically and call it like so
 `CURVE_ETH_POOL.call{value: amount}{(
            abi.encodeWithSignature("add_liquidity(uint256[],uint256)", amounts, min_mint_amount)
        );`

**Comment by securitygrid** [comment]
Escalate:
#42 and #105 are same issue. They should be merged.
The entire codebase does not provide `payable` functions for users, then the bank does not hold eth. so the protocol is not designed to interact with the ETH pool.
valid Low.

**Comment by sherlock-admin2** [comment]
> Escalate:
> #42 and #105 are same issue. They should be merged.
> The entire codebase does not provide `payable` functions for users, then the bank does not hold eth. so the protocol is not designed to interact with the ETH pool.
> valid Low.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
> Escalate:
> #42 and #105 are same issue. They should be merged.
> The entire codebase does not provide `payable` functions for users, then the bank does not hold eth. so the protocol is not designed to interact with the ETH pool.
> valid Low.

Agree with wrong (de)duplication
This is a duplicate of #105 

There were some issues with (de)duplication. I would resolve like this.
#98 is the duplicate with #20 
#105 is duplicate with #42

**Comment by IAm0x52** [comment]
This is not a dupe of #105. This issue is saying that the selector will be incorrect because the interface doesn't properly declare the function as payable. #105 is pointing out that "ETH" in the context of Curve is `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` which will cause the `balanceOf` call to revert. Similar outcome but completely different root cause.

Additionally this issue is invalid because the function selector is not dependent on the modifiers and will be the same regardless.

I've attached a small file you can run in remix to show that lacking payable on the interface isn't an issue:

    contract payableSubContract {
    
        event print(uint256 myUint);
    
        function myFunction() external payable {
            emit print(1);
        }
    }
    
    interface IPayableSubContract {
        function myFunction() external;
    }
    
    contract payableCaller {
        function testFunction() external{
    
            IPayableSubContract myContract = IPayableSubContract(address(new payableSubContract()));
            myContract.myFunction();
        }
    }

Deploy payableCaller then call testFunction. This won't revert and will successfully emit the print event even though the interface is missing the payable modifier on myFunction.

**Comment by securitygrid** [comment]
My escalation refers to the protocol not being planned to interact with pools containing native tokens. Because I can't see any code processing native tokens

**Comment by hrishibhat** [comment]
@securitygrid The Sponsor confirms #105 
Can you elaborate as to where the code is expected to process native tokens if intends to use it?

**Comment by securitygrid** [comment]
If the protocol plans to interact with a pool containing native token, the following steps are missing:
1. unwrap weth
2. check 0xeeeeeeeeeeeeeeeeeeeeee
3. ICurvePool(pool).add_liquidity{value: xxx}()
4. After ICurvePool(pool).add_liquidity is called, wrap eth to weth.

dev may ignore a certain step, it is impossible to ignore all steps, so I think the codes in update3 is not planned to support pool containing native token.

**Comment by IAm0x52** [comment]
The protocol doesn't need all those steps a majority of the time. It's not handling the ETH directly in the contract. It adds single coin liquidity then removes single coin liquidity. As an example, the user would borrow CRV which would be single sided deposited into the CRV-ETH pool. Then when closing their position, the contracts would single sided withdraw the CRV, so it never handles any native ETH.

**Comment by securitygrid** [comment]
[CurveSpell](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/spell/CurveSpell.sol#L110) has no problem, but [ConvexSpell](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/spell/ConvexSpell.sol#L123) has problem.
#105 describes ConvexSpell.
agree [it](https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/42#issuecomment-1705984233)

BTW, there is another issue [here](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/spell/CurveSpell.sol#L278-L287), if the pool contains native token, ICurvePool(pool).remove_liquidity will transfer native token to this contract, causing tx revert because [this contract only receieve ether from weth contract](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/spell/BasicSpell.sol#L438).

**Comment by JosephSaw** [comment]
Just checking in now, there is evidence that the ETH Native Token is intended to be used. For example, in the mainnet deployment script it does seem that Curve ETH pools are part of the deployment process:

https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/deploy/mainnet/0-mainnet.deploy.ts#L665
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/deploy/mainnet/0-mainnet.deploy.ts#L683
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/deploy/mainnet/0-mainnet.deploy.ts#L776

Another evidence where in the test deployment script a Curve ETH pool was added as a strategy:
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/test/helpers/setup-curve-protocol.ts#L251

But only the first strategy (strategyIndex: 0), a non-ETH Pool was tested properly here:
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/test/spell/curve.spell.test.ts

As mentioned by @securitygrid:
> If the protocol plans to interact with a pool containing native token, the following steps are missing:
> 1. unwrap weth
> 2. check 0xeeeeeeeeeeeeeeeeeeeeee
> 3. ICurvePool(pool).add_liquidity{value: xxx}()
> 4. After ICurvePool(pool).add_liquidity is called, wrap eth to weth.

I believe the assumption here on the Blueberry dev side is that they are assuming Curve pools uses Wrapped ETH instead of Native ETH, so therefore they don't have to unwrap it. But that assumption is wrong, which is why I created this issue to inform the devs that interacting with ETH native pools on curve will need to use Native ETH instead of Wrapped ETH.

As for the small POC by @securitygrid here https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/42#issuecomment-1705742811:
> Deploy payableCaller then call testFunction. This won't revert and will successfully emit the print event even though the interface is missing the payable modifier on myFunction.

This is only true if you are trying to call it without transferring ETH. If you do try to transfer ETH, i.e. adding ETH liquidity, the contract will not even be able to compiled such as below:
![image](https://github.com/sherlock-audit/2023-07-blueberry-judging/assets/28586597/aaa5c407-66a8-452f-addb-863b3e729825)

**Suggestion Update For Blueberry Devs:**
1. You will need to unwrap your WETH before transferring it to Curve as Liquidity
2. As highlighted by @securitygrid, when trying to remove ETH liquidity your contract will need to be able to receive the ETH via a fallback or receive function

**Comment by securitygrid** [comment]
> The protocol doesn't need all those steps a majority of the time. It's not handling the ETH directly in the contract. It adds single coin liquidity then removes single coin liquidity. As an example, the user would borrow CRV which would be single sided deposited into the CRV-ETH pool. Then when closing their position, the contracts would single sided withdraw the CRV, so it never handles any native ETH.


@JosephSaw borrowToken is CRV not native token.

**Comment by JosephSaw** [comment]
@securitygrid 

The issue I am trying to raise isn't about borrowing.

It is about:
1. Trying to add ETH liquidity to Curve ETH pools will not work
_And thanks to you pointing it out_
2. Withdrawing ETH liquidity from ETH Curve pools also will not work without a receive/fallback function

**Comment by hrishibhat** [comment]
@JosephSaw 
https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/42#issuecomment-1705742811
As pointed in the above comment the issue of function signature you mention in this issue does not seem to be a valid issue. Do you have additional comments wrt to that?

**Comment by JosephSaw** [comment]
@hrishibhat 

Yes, function signature comment was a mistake, but I believe the primary issue still stands, if the contract doesn't properly send Native Eth as a value the ETH liquidity will not be added properly to Curve ETH pools.

**Comment by hrishibhat** [comment]
@JosephSaw Yes but your issue does not identify the underlying issue as to why the native eth will not work.

**Comment by JosephSaw** [comment]
@hrishibhat 

Yes it does:
> All ETH related pools are payable functions, which expects a msg.value when calling the add_liquidity function.

> But Curve ETH pools uses payable functions where the msg.value is mandatory like so:

And the solution:
_After unwrapping Wrapped ETH to Native ETH_
> iii. If it is, you can add liquidity using code like so: CURVE_ETH_POOL.add_liquidity{value: amount}([amount, 0], 0);

Particularly, `{value: amount}`, to interact with a payable function sending ETH

**Comment by hrishibhat** [comment]
@JosephSaw 
While the lines taken out of context from your issue description can be subject to interpretations, I think reading the whole vulnerability detail section clearly fails to describe the root cause and identifies it incorrectly.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #105 
After further review considering although this issue makes certain incorrect assumptions it also mentions the underlying issue similar to #105. Hence considering this a duplicate of the same.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/42/#issuecomment-1693624149): accepted
